import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from 'react';
import MyCard from '../compontents/Card/card';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MyCard />
        <div className={styles.cloud1}></div>
        <div className={styles.cloud2}></div>
        <div className={styles.cloud3}></div>
      </main>
    </>
  );
}
