name: Deploy
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        DIST_ID: ${{ secrets.CLOUDFRONT_ID }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install application dependancies
        run: npm install
      - name: build project assets
        run: npm run build
      - name: upload static website
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: aws s3 sync out/ s3://${{ secrets.AWS_BUCKET_NAME }}
